### ISSUE TITLE
can the lib parse a .config file?

### ISSUE THREAD

**Issue by Ncerzzk** [Mcdostone/nom-kconfig#22]
for example, if I have parsed a Kconfig file,
I need a .config to do some config, if this lib have already support it or any plans? 

Thank you for great work!

**Comment by Mcdostone** [comment]
Hi @Ncerzzk 

Do you have any examples of what you would like to parse? I'm not sure to understand your request.
To me, a `.config` file is just environments variables gathered in a file. It's straightforward to parse them.

*Example from the linux kernel repository*:
```
#
# Processor type and features
#
CONFIG_SMP=y
CONFIG_X86_FEATURE_NAMES=y
CONFIG_X86_X2APIC=y
CONFIG_X86_MPPARSE=y
# CONFIG_GOLDFISH is not set
```

**Comment by Ncerzzk** [comment]
> Hi @Ncerzzk,
> 
> Do you have any examples of what you would like to parse? I'm not sure to understand your request. To me, a `.config` file is just environment variables gathered in a file. It's straightforward to parse them.
> 
> _Example from the linux kernel project_:
> 
> ```
> #
> # Processor type and features
> #
> CONFIG_SMP=y
> CONFIG_X86_FEATURE_NAMES=y
> CONFIG_X86_X2APIC=y
> CONFIG_X86_MPPARSE=y
> # CONFIG_GOLDFISH is not set
> ```

Thank you. This .config is what I refered before.
While I hope that I can achieve that:

when I set `CONFIG_SMP=y` in .config
I can get the 'value' of SMP is True when I traverse the entries of parsed Kconfig.

**Comment by Mcdostone** [comment]
What do you "mean" the 'value' of `SMP` ? According to the [kconfig specification](https://www.kernel.org/doc/html/next/kbuild/kconfig-language.html#menu-attributes), there is no way to define a value for a config entry. There is a `default` attribute but its purpose is completely different.

**Comment by Ncerzzk** [comment]
emm, yes, the kconfig didn't define the 'value' of the config entry.  While storing a value fore config entry is useful, for example to check the SMP config is set true of false.
I know that this may be out the box of the "Kconfig parser" lib ...

**Comment by Mcdostone** [comment]
Indeed, it sounds  out of the box of this parsing library. Fortunately, the API of the crate is open so you should be able to implement this feature in your project:


```rust
use nom_kconfig::{parse_kconfig, KconfigFile, KconfigInput};
use std::path::PathBuf;

// curl https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.4.9.tar.xz | tar -xJ -C /tmp/
fn main() -> Result<(), Box<dyn std::error::Error>> {
    let kconfig_file = KconfigFile::new(
        PathBuf::from("/tmp/linux-6.4.9"), // Root directory of your kconfig project, needed to parse 'source' entries
        PathBuf::from("/tmp/linux-6.4.9/Kconfig"),
    );
    let input = kconfig_file.read_to_string()?;
    let kconfig = parse_kconfig(KconfigInput::new_extra(&input, kconfig_file)).unwrap();

    for entry in kconfig.1.entries {
        match entry {
            nom_kconfig::Entry::Config(config) => {
                // TODO do something here
            }
            nom_kconfig::Entry::Choice(choice) => {
                // TODO do something here
            }
            nom_kconfig::Entry::MenuConfig(menu_config) => {
                // TODO do something here
            }
            nom_kconfig::Entry::Menu(menu) => {
                // TODO do something here
            }
            nom_kconfig::Entry::Source(source) => {
                // TODO do something here
            }
            nom_kconfig::Entry::If(if_block) => {
                // TODO do something here
            }
            nom_kconfig::Entry::MainMenu(main_menu) => {
                // TODO do something here
            }
            nom_kconfig::Entry::Comment(_) => (),
            nom_kconfig::Entry::VariableAssignment(_) => (),
            nom_kconfig::Entry::FunctionCall(_) => (),
            nom_kconfig::Entry::Function(_) => ()
        }
    }
    Ok(())
}
```

I close this issue, let me know if you have any other questions!
