### ISSUE TITLE
Parsing error on def_bool

### ISSUE THREAD

**Issue by JVMerkle** [Mcdostone/nom-kconfig#57]
Hi!
First of all thanks for your parser.

I have troubles parsing some Linux Kconfig files, e.g. this file here:

```kconfig
# Linux v6.10.9: arch/x86/Kconfig.assembler

config AS_WRUSS
	def_bool $(as-instr64,wrussq %rax$(comma)(%rbx))
	help
	  Supported by binutils
```

yields

```text
input: LocatedSpan { offset: XXXX, line: XX, fragment: ")\n\thelp\n\t  Supported by binutils\n",
extra: KconfigFile { root_dir: "XXX/linux", file: "XXX/linux/arch/x86/Kconfig.assembler" }
}, code: Eof
```

It seems like the problem comes somewhere from `def_bool`.

**Comment by JVMerkle** [comment]
It seems like the parser does not like the extra parenthesis. Here a minimal non-working example:

```kconfig
config TEST
	def_bool $(hey (%rbx))
```

**Comment by Mcdostone** [comment]
Hi, Thank you for giving me an example. I'll take a look by the end of the week.

**Comment by Mcdostone** [comment]
Hey, a temporary fix is available here:
```toml
nom-kconfig = { git = "git@github.com:Mcdostone/nom-kconfig.git",  branch = "fix/parse-bool" }
```

Can you tell me if it works?
I've never seen a macro parameter between parenthesis in the linux kernel codebase.  Does it mean something  particular? What's the output?

**Comment by JVMerkle** [comment]
Hey @Mcdostone,

awesome, that was quick! Yes the fix works.
I am collecting all configuration options for x86 in for different versions, but this one file made some trouble. Other than that from what I can tell your parser works great (for SRCARCH x86 at least). Regarding the meaning of this particular `def_bool`: I don't know what it does or what it means :smile: 

Thanks!

**Comment by JVMerkle** [comment]
No pressure, but thanks a lot.

**Comment by Mcdostone** [comment]
`0.2.1` is available ! Enjoy
